name: lrsadmin
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # firebase dependencies
  firebase_core: ^1.0.2
  cloud_firestore: ^1.0.3
  firebase_auth: ^1.0.1
  firebase_storage: ^8.0.1

  # redux dependencies
  redux: ^4.0.0+3
  flutter_redux: ^0.7.0

  # Built dependencies
  built_value: ^8.0.0
  built_collection: ^5.0.0

  ionicons: ^0.1.2
  auto_size_text: ^2.1.0
  cached_network_image: ^2.5.0
  flutter_spinkit: ^5.0.0
  # image_picker: ^0.6.7+22
  image_picker: ^0.7.4
  # path_provider: ^1.6.27
  path_provider: ^2.0.1
  # permission_handler: ^5.1.0+2
  permission_handler: ^6.1.1
  flutter_native_image: ^0.0.5+3
  smooth_star_rating: ^1.1.1
  timeago: ^3.0.2
  fluttertoast: ^8.0.3
  modal_bottom_sheet: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.2
  built_value_generator: ^8.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/lrs_logo.JPG
    - assets/images/regentlogo.jpeg
  fonts:
    - family: Jost
      fonts:
        - asset: assets/fonts/Jost-Regular.ttf
